name: Dispatch PiccoloMultiDocs
on:
  workflow_run:
    workflows: ["Documentation"]
    types:
      - completed
    branches:
      - main # Only run when docs.yml completes on main branch
jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && startsWith(github.event.workflow_run.head_ref, 'refs/tags/')
    steps:
      - name: Dispatch PiccoloMultiDocs workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: harmoniqs/PiccoloMultiDocs.jl
          event-type: rebuild-docs
          client-payload: '{"ref": "${{ github.event.workflow_run.head_ref }}"}'
